apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: actions-runner-autoscaler
spec:
  minReplicas: 4
  maxReplicas: 16
  scaleTargetRef:
      name: actions-runner-deployment-link
