apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: actions-runner-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
      name: actions-runner-deployment-link
