apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: actions-runner-autoscaler
spec:
  minReplicas: 3
  maxReplicas: 9
  scaleTargetRef:
      name: actions-runner-deployment-tobedeleted
