apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../templates/
namespace: github-actions-runner-${RUNNER_ENVIRONMENT}
nameSuffix: -${RUNNER_ENVIRONMENT}
commonLabels:
  environment: ${RUNNER_ENVIRONMENT}
patchesStrategicMerge:
- set-auto-scaler-props.yaml
- set-runner-deployment-props.yaml
