apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: actions-runner-autoscaler
spec:
  minReplicas: 8
  maxReplicas: 20
  scaleTargetRef:
      name: actions-runner-deployment-barfoo
