name: Scaling test for runner env pulipan

on:
  workflow_dispatch:
    inputs:
      numberJobs:
        description: 'Number of parallel jobs (should stay below 100)'
        required: true
        default: '5'

jobs:
  generate-matrix:
    name: "Generate jobs for pulipan"
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    runs-on: [ self-hosted ]
    steps:
      - name: generate-matrix
        id: generate-matrix
        run: echo "::set-output name=matrix::[`seq -s , ${{ github.event.inputs.numberJobs }}`]"

  stress:
    name: "Stress tests for pulipan"
    runs-on: [ pulipan ]
    needs: [generate-matrix]

    strategy:
      matrix:
        job-number: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
    - name: Stress test ${{ matrix.job-number }} of env pulipan
      run: echo "Matrix version ${{ matrix.job-number }}" && stress --cpu 1 --timeout $((RANDOM%120+60))
